### ISSUE TITLE
Backdrop only showing at step 2 onwards. Step one is without backdrop. 

### ISSUE THREAD

**Issue by wsdt** [xcarpentier/rn-tourguide#160]

**Comment by cip123** [comment]
I started experiencing this when I upgraded to expo 52, it was working fine before.

**Comment by maituanviet-dev** [comment]
same issue

**Comment by bakhiem** [comment]
same issue when I turn on new architecture

**Comment by kristof-kovacs** [comment]
Same issue here.

**Comment by kristof-kovacs** [comment]
Fixed this with a simple patch! 

[rn-tourguide+3.3.2.patch](https://github.com/user-attachments/files/19782004/rn-tourguide%2B3.3.2.patch)

**Comment by joaquinvaz** [comment]
> Fixed this with a simple patch!
> 
> [rn-tourguide+3.3.2.patch](https://github.com/user-attachments/files/19782004/rn-tourguide%2B3.3.2.patch)

Thanks! but it's not showing the first element, like it shows just the opacity background and it doesn't show the element to focus on

**Comment by el-lsan** [comment]
> Fixed this with a simple patch!
> 
> [rn-tourguide+3.3.2.patch](https://github.com/user-attachments/files/19782004/rn-tourguide%2B3.3.2.patch)

@kristof-kovacs Thanks for sharing but unfortunately the patch did not fix the issue.

**Comment by Jigs6720** [comment]
same issue here

**Comment by EthanMetal1** [comment]
Please try this solution if the above isn't working for you
https://github.com/xcarpentier/rn-tourguide/issues/162#issuecomment-3349198266
